site_name: REID Data Scraping Documentation
theme:
  name: material
nav:
  - Overview: index.md
  - How it work: how-it-work.md
  - How to use: how-to-use.md
  - Development: development.md
  - Work with Captcha: passing-captcha.md
plugins:
  - mermaid2
